version: '3.7'
services:
  postgresql:
    image: postgresql:12
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_USER=app
      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
